### ISSUE TITLE
Improve `models.create_all()`

### ISSUE THREAD

**Issue by lovelydinosaur** [encode/dashboard#11]
The `orm` pre-release includes `models.create_all()` and `models.drop_all()` support, however they're very naive right now.

Required improvements:

* Use `query.compile(dialect-...)` rather than just casting the DDL expression to a string. https://github.com/encode/databases/issues/40
* Proper FK constraint support. (Create FK constraints *after* table creation, where required.)

**Comment by aminalaee** [comment]
Now we're using sqlalchemy `create_async_engine` and use database and tables using `metadata.create_all`, so we don't have to `compile` the query for backends.
I guess this can be closed now.
